name: dart_mv
author: Julien Castelain <jcastelain@gmail.com>
description:
  A minimalist "model view" implementation
  in Dart.
homepage: https://github.com/julien/dart_mv
version: 0.0.9
dependencies:
  unittest: any
  browser: any


